# Generated by Django 6.0.7 on 2026-08-01 02:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DynamicTableMetadata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table_name', models.CharField(help_text='Physical table name in the dynamic_data schema', max_length=200, unique=True)),
                ('display_name', models.CharField(help_text='Human-readable name shown in the UI', max_length=300)),
                ('description', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('creating', 'Creating'), ('active', 'Active'), ('failed', 'Failed'), ('archived', 'Archived')], default='creating', max_length=20)),
                ('error_message', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'dynamic_table_metadata',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status'], name='dynamic_tab_status_814d6d_idx'), models.Index(fields=['table_name'], name='dynamic_tab_table_n_b6e497_idx')],
            },
        ),
        migrations.CreateModel(
            name='DynamicColumnMetadata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('column_name', models.CharField(max_length=200)),
                ('column_type', models.CharField(help_text='Type key from DYNAMIC_TABLE_ALLOWED_TYPES', max_length=50)),
                ('nullable', models.BooleanField(default=True)),
                ('default_value', models.TextField(blank=True, null=True)),
                ('max_length', models.IntegerField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('position', models.IntegerField(default=0, help_text='Column display order')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='columns', to='dynamic_models.dynamictablemetadata')),
            ],
            options={
                'db_table': 'dynamic_column_metadata',
                'ordering': ['table', 'position'],
                'indexes': [models.Index(fields=['table', 'is_deleted'], name='dynamic_col_table_i_73f492_idx')],
                'unique_together': {('table', 'column_name')},
            },
        ),
    ]
