# Generated by Django 6.0.7 on 2026-08-01 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dynamic_models', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table_name', models.CharField(help_text='The dynamic table this Yjs document belongs to', max_length=200, unique=True)),
                ('ydoc_state', models.BinaryField(help_text='Full Yjs document state encoded as update bytes')),
                ('version', models.IntegerField(default=1, help_text='Monotonic version counter for conflict detection')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'document_state',
                'indexes': [models.Index(fields=['table_name'], name='document_st_table_n_b21c5a_idx')],
            },
        ),
    ]
